#数据源
spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://99.100.3.134:3306/film?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  row-bounds-with-count: true