spring:
  session:
    store-type: redis
    timeout: 5m
    redis:
      flush-mode: on_save
      namespace: redis:session
  redis:
    host: 192.168.10.64
    port: 6379
    database: 0
  application:
    name: spring-session
server:
  port: 80
  servlet:
    session:
      timeout: 30m