# 高阶语法 https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines/21699210#21699210
param:
  student:
    name: jack
    age: 12
    birth: 2018/11/11
    hobbies:
      - eat
      - drink
    info: {key1: aa,key2: bb}
binder:
  name: binder
  add: chinaanhui
ph:
  p1: ${param.student.age}
  p2: ${random.int}
# Map<String,Set<String>>
nested:
  setInMap:
    key1:
      - value1
      - value2
    key2:
      - value3
      - value4
