# 高阶语法 https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines/21699210#21699210
param:
  student:
    name: jack
    age: 12
    birth: 2018/11/11
    hobbies:
      - eat
      - drink
    info: { key1: aa,key2: bb }
binder:
  name: binder
  add: chinaanhui
ph:
  p1: ${param.student.age}
  p2: ${random.int}
# Map<String,Set<String>>
nested:
  setInMap:
    key1:
      - value1
      - value2
    key2:
      - value3
      - value4
risk-table:
  # edit using https://jshare.com.cn/demos/hhhhiz?hc-theme=dark-unica
  one: [
    [ 0,0,1 ],[ 0,1,1 ],[ 0,2,1 ],[ 0,3,1 ],[ 0,4,1 ],
    [ 1,0,2 ],[ 1,1,1 ],[ 1,2,1 ],[ 1,3,1 ],[ 1,4,1 ],
    [ 2,0,2 ],[ 2,1,2 ],[ 2,2,1 ],[ 2,3,1 ],[ 2,4,1 ],
    [ 3,0,3 ],[ 3,1,2 ],[ 3,2,2 ],[ 3,3,1 ],[ 3,4,1 ],
    [ 4,0,4 ],[ 4,1,3 ],[ 4,2,2 ],[ 4,3,3 ],[ 4,4,1 ] ]
  tow: [
    [ 0,0,2 ],[ 0,1,1 ],[ 0,2,1 ],[ 0,3,1 ],[ 0,4,1 ],
    [ 1,0,2 ],[ 1,1,2 ],[ 1,2,1 ],[ 1,3,1 ],[ 1,4,1 ],
    [ 2,0,3 ],[ 2,1,2 ],[ 2,2,2 ],[ 2,3,1 ],[ 2,4,1 ],
    [ 3,0,3 ],[ 3,1,3 ],[ 3,2,2 ],[ 3,3,2 ],[ 3,4,1 ],
    [ 4,0,4 ],[ 4,1,4 ],[ 4,2,3 ],[ 4,3,2 ],[ 4,4,2 ] ]
  three: [
    [ 0,0,2 ],[ 0,1,2 ],[ 0,2,1 ],[ 0,3,1 ],[ 0,4,1 ],
    [ 1,0,3 ],[ 1,1,2 ],[ 1,2,2 ],[ 1,3,1 ],[ 1,4,1 ],
    [ 2,0,3 ],[ 2,1,3 ],[ 2,2,2 ],[ 2,3,2 ],[ 2,4,1 ],
    [ 3,0,4 ],[ 3,1,3 ],[ 3,2,3 ],[ 3,3,2 ],[ 3,4,2 ],
    [ 4,0,4 ],[ 4,1,4 ],[ 4,2,4 ],[ 4,3,3 ],[ 4,4,2 ] ]
  four: [
    [ 0,0,3 ],[ 0,1,2 ],[ 0,2,2 ],[ 0,3,1 ],[ 0,4,1 ],
    [ 1,0,3 ],[ 1,1,3 ],[ 1,2,2 ],[ 1,3,2 ],[ 1,4,1 ],
    [ 2,0,4 ],[ 2,1,3 ],[ 2,2,3 ],[ 2,3,2 ],[ 2,4,2 ],
    [ 3,0,4 ],[ 3,1,4 ],[ 3,2,3 ],[ 3,3,3 ],[ 3,4,2 ],
    [ 4,0,4 ],[ 4,1,4 ],[ 4,2,4 ],[ 4,3,4 ],[ 4,4,3 ] ]
  five: [
    [ 0,0,3 ],[ 0,1,3 ],[ 0,2,2 ],[ 0,3,2 ],[ 0,4,1 ],
    [ 1,0,4 ],[ 1,1,3 ],[ 1,2,3 ],[ 1,3,2 ],[ 1,4,2 ],
    [ 2,0,4 ],[ 2,1,4 ],[ 2,2,3 ],[ 2,3,3 ],[ 2,4,2 ],
    [ 3,0,4 ],[ 3,1,4 ],[ 3,2,4 ],[ 3,3,3 ],[ 3,4,3 ],
    [ 4,0,4 ],[ 4,1,4 ],[ 4,2,4 ],[ 4,3,4 ],[ 4,4,4 ] ]