spring:
  application:
    name: tdscxy
  datasource:
    hikari:
      idle-timeout: 0 #永不超时
      max-lifetime: 0 #永不死亡
      minimum-idle: 1 #至少一个链接
      maximum-pool-size: 10 #最多10个链接
      connection-init-sql: 'set names utf8mb4'
      connection-timeout: 30000
    dynamic:
      primary: db1
      datasource:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://119.23.252.178:3306/cloudDB01
          username: root
          password: shang2010
        db2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://119.23.252.178:3306/cloudDB02
          username: root
          password: shang2010
mybatis-plus:
  #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: 'classpath:mappers/*Mapper.xml'
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: top.seefly.springmybatisplusds.entity
server:
  port: 8888
  servlet:
    context-path: /tdscxy