spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #指定驱动
    type: com.zaxxer.hikari.HikariDataSource #指定数据源类型
    schema: classpath:db/schema-h2.sql #指定初始化ddl
    data: classpath:db/data-h2.sql #指定初始化dml
    initialization-mode: never #sql语句初始化策略
    hikari:
      initialization-fail-timeout: 3000
      connection-timeout: 1500
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 15
      max-lifetime: 60000
      connection-init-sql: set names utf8mb4
      connectionTestQuery: select 1 from DUAL
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.seefly.springmybaits.entity
  type-enums-package: org.seefly.springmybaits.enums
logging:
  level:
    com.devloper.joker: debug
