spring:
  redis:
    host: localhost
    port: 49153
    database: 15
    lettuce:
      pool:
        max-active: 6
        max-wait: 30s
        max-idle: 8
        min-idle: 0
    password: redispw
  application:
    name: redisB
#debug: true redis://default:redispw@localhost:49153

