spring:
  redis:
    host: ${REDIS_HOST}
    port: 6679
    database: 15
    lettuce:
      pool:
        max-active: 6
        max-wait: 30s
        max-idle: 8
        min-idle: 0
  application:
    name: redisB
#debug: true

