#server.servlet.path指定项目访问路径，终于找到了
server:
  port: 80
spring:
  profiles:
    active: dev
binder:
  name: binder
  add: chinaanhui
#debug模式会在springboot启动的时候打印哪些自动配置类启用了哪些没有
#debug: true
#  profiles:
#    active: dev
---
spring:
  profiles: prod