#server.servlet.path指定项目访问路径，终于找到了
server:
  port: 8080
spring:
  profiles:
    active: dev
#debug模式会在springboot启动的时候打印哪些自动配置类启用了哪些没有
#debug: true
#  profiles:
#    active: dev

---
spring:
  profiles: dev
---
spring:
  profiles: prod