spring:
  datasource:
    username: root
    password: shang2010
    url: jdbc:mysql://119.23.252.178:3306/website?useUnicode=true&characterEncoding=utf8&autoReconnect=true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  row-bounds-with-count: true